### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [samuelmbp/calculator#3]
# Feedback

## Requirements

- Deployed website
- Github Repo:
  - README.md
  - 15 commits
- Be responsive and built mobile-first, it should work on different screen widths
- Accept a minimum of 2 inputs, perform an operation and return the output.
- DO NOT USE `eval()`
- Code is highly readable (good naming and indented correctly)

### Let's Build

- A working Calculator
- Practice using Git and GitHub flow
- Apply what you are learning.
  - SCSS
  - BEM

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/02-javascript-typescript/calculator-marking-scheme.md)

| Category             | Score     |
| -------------------- | --------- |
| Version Control      | 10 / 10   |
| Site Output          | 40 / 45   |
| Readability          | 20 / 20   |
| Responsiveness       | 10 / 10   |
| Code Knowledge & Use | 20 / 25   |
| Total Score          | 100 / 110 |

#### Positive

- What a project, this has been an obvious success for you! I like that you have found a way to challenge yourself by making the project as well-rounded as possible. You have been focused on code quality and the project reflects this.
  - You probably could have finished it in a couple of afternoons but have kept on adding & refactoring it, this is great.
  - You are going to keep this up, it does make reviewing projects more interesting :)
- The UI Looks great, it is clean and clear how to interact with it.
  - Highlighting the operator that is selected is great.

#### Constructive

- You can delete `<link rel="icon" type="image/svg+xml" href="/vite.svg" />` from the HTML file.
- With your styles, all of the individual selectors you have for each button `.zero`, `.one ` would be considered a block so should be outside the `.calculator` class as they are not named as elements.
- At the moment you are nesting too deep you have `.calculator` > `&__buttons` > `.calculator__button` this is BLOCK > ELEMENT > ELEMENT. it should only be BLOCK > ELEMENT.

```scss
.calculator {
  position: relative;
  border-radius: 22px;
  overflow: hidden;
  box-shadow: 0 0 25px 0 rgba(0, 0, 0, 0.3);

  .is-pressed:focus {
    background-color: $button-focus-color;
  }

  &__display {
    font-family: "Orbitron", sans-serif;
    font-optical-sizing: auto;
    font-style: normal;
    width: 240px;
    padding: 26px 18px;
    background-color: $display-color;
    color: $light-text-color;
    font-size: 26px;
    text-align: right;
    border: none;
  }

  &__buttons {
    display: grid;
    grid-gap: 2px;
    grid-template-columns: repeat(4, auto);
    background-color: $button-bg-color;
    grid-template-areas:
      ". . . ."
      "seven eight nine modulus"
      "four five six delete"
      "one two three equal"
      "zero decimal clear equal";
  }
  // ONLY BLOCK__ELEMENT NOW
  // - NOT NESTED IN &__buttons SELECTOR
  &__button {
    position: relative;
    font-size: 22px;
    width: 68px;
    min-height: 80px;
    border: 0;
    background: $light-text-color;
  }
}

// MOVED OUTSIDE AS NAMED AS A BLOCK
.zero {
  grid-area: zero;
}
.one {
  grid-area: one;
}
// ...
```

#### Positive

- There are a lot of positives in your Typescript, probably too many for me to note down but I will try.
  - I am so glad you separated and grouped your functionality into specific files. They are named well and each has a clear concern, making the codebase easier to understand.
    - It would have been tough if this was all in one file.
  - You have a great example of using event propagation and delegation to simplify your functionality. Why listen to events on individual buttons when you can listen to one event on the container?
- All in all a great project, one of the most well-rounded calculators I have seen.

#### Constructive

- You can update where you get access to the `.textContent`.

  - If you hover over `.textContent` you can see it is a `string | null` type. It is a `string` if there is text content in the HTML element and `null` if not.
  - This is a case where you know better than Typescript and you know your HTML will have content so it will be a `string`. This means you can cast it `calculatorDisplay.textContent as string;` instead of using nullish coalescing.
  - `const displayValue = calculatorDisplay.textContent ?? undefined;` -> `const displayValue = calculatorDisplay.textContent as string;`

- I think you can refactor your `handleOperatorButton` function, as I do not think it is doing what you want it to do. The `is-pressed` class stays on your elements. I think you have a way around this but the snippet below should explain why.

```typescript
export const handleOperatorButton = (
  calculatorButtons: HTMLDivElement,
  calculator: HTMLDivElement,
  button: HTMLElement,
  displayValue: string | undefined
) => {
  // Release operator pressed state
  // [calculatorButtons.children] IS A NESTED ARRAY
  // - THE FIRST ELEMENT IS A HTML COLLECTION OF YOUR BUTTONS -> [ [ HTML ELEMENTS INSIDE THIS ARRAY ... ] ]
  // THIS MEANS YOUR operatorButtons IS ALWAYS A EMPTY ARRAY AS IT LOOPS OTHER ONE ELEMENT AND IT RETURNS FALSE
  const operatorButtons = [calculatorButtons.children].filter(button => {
    if (!(button instanceof HTMLElement)) return false;
    button.dataset.buttonType === "operator";
  });
  // THIS CODE DOESN'T SEEM TO DO ANYTHING & THE is-pressed CLASS WILL STAY ON ELEMENTS AFTERWARDS
  operatorButtons.forEach(button => {
    if (!(button instanceof HTMLElement)) return false;
    button.classList.remove("is-pressed");
  });

  button.classList.add("is-pressed");
  calculator.dataset.firstValue = displayValue;
  calculator.dataset.operator = button.dataset.key;
};

// COULD BE

export const handleOperatorButton = (
  calculatorButtons: HTMLDivElement,
  calculator: HTMLDivElement,
  button: HTMLElement,
  displayValue: string | undefined
) => {
  // IF YOU USE THE ... SPREAD OPERATOR YOU CAN TURN THE HTML COLLECTION INTO AN ARRAY OF ELEMENTS
  const buttonElements = [...calculatorButtons.children];

  buttonElements.forEach(button => {
    // THIS MEANS YOU CAN LOOP CHECK IF IT HAS THE CLASS & REMOVE IF SO
    if (button.classList.contains("is-pressed")) {
      button.classList.remove("is-pressed");
    }
  });

  // WIH THIS SOLUTION THE is-pressed GETS REMOVED FROM THE HTML ELEMENTS

  button.classList.add("is-pressed");
  calculator.dataset.firstValue = displayValue;
  calculator.dataset.operator = button.dataset.key;
};
```

- Let's get some unit tests in the project!
  - Your `calculate` function is an obvious one to test that should be fairly straightforward.
  - You could also research how to check that a test throws an Error :)

---
